name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install Steam
      run: |
        Invoke-WebRequest "https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe" -OutFile "SteamSetup.exe"
        Start-Process -FilePath "SteamSetup.exe" -ArgumentList "/S" -Wait
    - name: Install BlueStacks 5
      run: |
        Invoke-WebRequest "https://cdn3.bluestacks.com/downloads/windows/BlueStacksInstaller_5.3.110.1017_native_68e4b1cb1a916f8c0b1cd75d5a478fa3.exe" -OutFile "BlueStacks5Setup.exe"
        Start-Process -FilePath "BlueStacks5Setup.exe" -ArgumentList "/S" -Wait
    - name: Install BlueStacks 4
      run: |
        Invoke-WebRequest "https://cdn3.bluestacks.com/downloads/windows/bgp64installer-ubi-native.exe" -OutFile "BlueStacks4Setup.exe"
        Start-Process -FilePath "BlueStacks4Setup.exe" -ArgumentList "/S" -Wait
    - name: Set Chrome as default browser
      run: |
        $RegPath = "HKLM:\SOFTWARE\Classes\http\shell\open\command"
        $RegValue = "chrome.exe"
        Set-ItemProperty -Path $RegPath -Name "(Default)" -Value $RegValue
        $RegPath = "HKLM:\SOFTWARE\Classes\https\shell\open\command"
        Set-ItemProperty -Path $RegPath -Name "(Default)" -Value $RegValue
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
