name: PC

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install Steam
      run: |
        Invoke-WebRequest "https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe" -OutFile "SteamSetup.exe"
        Start-Process -FilePath "SteamSetup.exe" -ArgumentList "/S" -Wait
    - name: Install Epic Games Launcher
      run: |
        Invoke-WebRequest "https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi" -OutFile "EpicGamesLauncherInstaller.msi"
        Start-Process -FilePath "msiexec.exe" -ArgumentList "/i", "EpicGamesLauncherInstaller.msi", "/quiet", "/norestart" -Wait
    - name: Install WinRAR 64-bit
      run: |
        Invoke-WebRequest "https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-700.exe" -OutFile "WinRARInstaller.exe"
        Start-Process -FilePath "WinRARInstaller.exe" -ArgumentList "/S" -Wait
    - name: Install OBS Studio
      run: |
        Invoke-WebRequest "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-27.2.3-Full-Installer-x64.exe" -OutFile "OBS-Studio-Installer.exe"
        Start-Process -FilePath "OBS-Studio-Installer.exe" -ArgumentList "/S" -Wait
    - name: Install Bluestacks
      run: |
        Invoke-WebRequest "https://cloud.bluestacks.com/api/getdownloadnow?platform=win&win_version=10&mac_version=&client_uuid=4c7bafd4-8bdf-42ad-adb9-939dd6c7f54d&app_pkg=&platform_cloud=%257B%2522description%2522%253A%2522Microsoft%2520Edge%2520123.0.0.0%2520on%2520Windows%252010%252064-bit%2522%252C%2522layout%2522%253A%2522Blink%2522%252C%2522manufacturer%2522%253Anull%252C%2522name%2522%253A%2522Microsoft%2520Edge%2522%252C%2522prerelease%2522%253Anull%252C%2522product%2522%253Anull%252C%2522ua%2522%253A%2522Mozilla%252F5.0%2520(Windows%2520NT%252010.0%253B%2520Win64%253B%2520x64)%2520AppleWebKit%252F537.36%2520(KHTML%252C%2520like%2520Gecko)%2520Chrome%252F123.0.0.0%2520Safari%252F537.36%2520Edg%252F123.0.0.0%2522%252C%2522version%2522%253A%2522123.0.0.0%2522%252C%2522os%2522%253A%257B%2522architecture%2522%253A64%252C%2522family%2522%253A%2522Windows%2522%252C%2522version%2522%253A%252210%2522%257D%257D&preferred_lang=en&utm_source=&utm_medium=&gaCookie=GA1.1.936716040.1713376125&gclid=&clickid=&msclkid=&affiliateId=&offerId=&transaction_id=&aff_sub=&first_landing_page=https%253A%252F%252Fwww.bluestacks.com%252F&referrer=https%253A%252F%252Fwww.bing.com%252F&download_page_referrer=https%3A%2F%2Fwww.bluestacks.com%2Fdownload.html&utm_campaign=homepage-dl-button-en&user_id=experiment_variant&exit_utm_campaign=download-page-dl-button-en&incompatible=false&bluestacks_version=bs5&device_memory=8&device_cpu_cores=4" -OutFile "BlueStacksInstaller.exe"
        Start-Process -FilePath "BlueStacksInstaller_5.21.150.1025_native.exe" -ArgumentList "/S" -Wait
    - name: Show Desktop icons
      run: |
        $desktopPath = [System.Environment]::GetFolderPath('Desktop')
        $shell = New-Object -ComObject WScript.Shell
        $icons = @{
            "User's Files" = "shell:Profile"
            "This PC" = "::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"
            "Network" = "shell:NetworkPlacesFolder"
            "Control Panel" = "shell:ControlPanelFolder"
            "Recycle Bin" = "shell:RecycleBinFolder"
        }
        foreach ($icon in $icons.Keys) {
            $iconPath = "$desktopPath\$icon.lnk"
            $targetPath = $icons[$icon]
            $shortcut = $shell.CreateShortcut($iconPath)
            $shortcut.TargetPath = $targetPath
            $shortcut.Save()
        }
    - name: Set Chrome as default web browser
      run: |
        $RegPath = "HKCU:\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice"
        Set-ItemProperty -Path $RegPath -Name "ProgId" -Value "ChromeHTML"
    - name: Change color mode to dark
      run: |
        reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize /v AppsUseLightTheme /t REG_DWORD /d 0 /f
        reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize /v SystemUsesLightTheme /t REG_DWORD /d 0 /f
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
    - name: Install Mega
      run: |
        Invoke-WebRequest "https://mega.nz/MEGAsyncSetup64.exe" -OutFile "MEGAsyncSetup64.exe"
        Start-Process -FilePath "MEGAsyncSetup64.exe" -ArgumentList "/S" -Wait
    - name: Install AnyDesk
      run: |
        Invoke-WebRequest "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDeskInstaller.exe"
        Start-Process -FilePath "AnyDeskInstaller.exe" -ArgumentList "/S" -Wait
