name: PC

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install Steam
      run: |
        Invoke-WebRequest "https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe" -OutFile "SteamSetup.exe"
        Start-Process -FilePath "SteamSetup.exe" -ArgumentList "/S" -Wait
    - name: Install Epic Games Launcher
      run: |
        Invoke-WebRequest "https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi" -OutFile "EpicGamesLauncherInstaller.msi"
        Start-Process -FilePath "msiexec.exe" -ArgumentList "/i", "EpicGamesLauncherInstaller.msi", "/quiet", "/norestart" -Wait
    - name: Install WinRAR 64-bit
      run: |
        Invoke-WebRequest "https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-700.exe" -OutFile "WinRARInstaller.exe"
        Start-Process -FilePath "WinRARInstaller.exe" -ArgumentList "/S" -Wait
    - name: Install OBS Studio
      run: |
        Invoke-WebRequest "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-27.2.3-Full-Installer-x64.exe" -OutFile "OBS-Studio-Installer.exe"
        Start-Process -FilePath "OBS-Studio-Installer.exe" -ArgumentList "/S" -Wait
    - name: Install Brave
      run: |
        Invoke-WebRequest "https://laptop-updates.brave.com/latest/winx64" -OutFile "BraveSetup.exe"
        Start-Process -FilePath "BraveSetup.exe" -ArgumentList "/S" -Wait
    - name: Install Opera
      run: |
        Invoke-WebRequest "https://download3.operacdn.com/pub/opera/desktop/81.0.4196.60/win/Opera_81.0.4196.60_Setup.exe" -OutFile "OperaSetup.exe"
        Start-Process -FilePath "OperaSetup.exe" -ArgumentList "/S" -Wait
    - name: Install Opera GX
      run: |
        Invoke-WebRequest "https://download3.operacdn.com/pub/opera_gx/desktop/80.0.4170.63/win/Opera_GX_80.0.4170.63_Setup.exe" -OutFile "OperaGXSetup.exe"
        Start-Process -FilePath "OperaGXSetup.exe" -ArgumentList "/S" -Wait
    - name: Install Vivaldi
      run: |
        Invoke-WebRequest "https://downloads.vivaldi.com/stable/Vivaldi.3.8.2259.42.exe" -OutFile "VivaldiSetup.exe"
        Start-Process -FilePath "VivaldiSetup.exe" -ArgumentList "/S" -Wait
    - name: Install UC Browser
      run: |
        Invoke-WebRequest "https://ucbrowserapp.com/ucbrowser/download/UCBrowser_V8.0.3.1413_58.0.3030.110_10000_win64_release.exe" -OutFile "UCBrowserSetup.exe"
        Start-Process -FilePath "UCBrowserSetup.exe" -ArgumentList "/S" -Wait
    - name: Show Desktop icons
      run: |
        $desktopPath = [System.Environment]::GetFolderPath('Desktop')
        $shell = New-Object -ComObject WScript.Shell
        $icons = @{
            "User's Files" = "shell:Profile"
            "This PC" = "::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"
            "Network" = "shell:NetworkPlacesFolder"
            "Control Panel" = "shell:ControlPanelFolder"
            "Recycle Bin" = "shell:RecycleBinFolder"
        }
        foreach ($icon in $icons.Keys) {
            $iconPath = "$desktopPath\$icon.lnk"
            $targetPath = $icons[$icon]
            $shortcut = $shell.CreateShortcut($iconPath)
            $shortcut.TargetPath = $targetPath
            $shortcut.Save()
        }
    - name: Set Chrome as default web browser
      run: |
        $RegPath = "HKCU:\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice"
        Set-ItemProperty -Path $RegPath -Name "ProgId" -Value "ChromeHTML"
    - name: Change color mode to dark
      run: |
        reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize /v AppsUseLightTheme /t REG_DWORD /d 0 /f
        reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize /v SystemUsesLightTheme /t REG_DWORD /d 0 /f
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
    - name: Install Mega
      run: |
        Invoke-WebRequest "https://mega.nz/MEGAsyncSetup64.exe" -OutFile "MEGAsyncSetup64.exe"
        Start-Process -FilePath "MEGAsyncSetup64.exe" -ArgumentList "/S" -Wait
    - name: Install AnyDesk
      run: |
        Invoke-WebRequest "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDeskInstaller.exe"
        Start-Process -FilePath "AnyDeskInstaller.exe" -ArgumentList "/S" -Wait
