name: PC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup ngrok
        run: |
          # Download ngrok
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          
          # Extract ngrok
          Expand-Archive ngrok.zip
          
          # Authenticate ngrok
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Download and Extract chroma_cur_black_s.zip
        run: |
          $downloadUrl = "https://github.com/Dizaaar/FREE-RDP/raw/main/chroma_cur_black_s.zip"
          $downloadPath = "C:\chroma_cur_black_s.zip"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
          Expand-Archive -Path $downloadPath -DestinationPath "C:\"

      - name: Install chroma_cur_black_s
        run: |
          cd C:\chroma_cur_black_s
          # Simulate right-click
          [System.Windows.Forms.SendKeys]::SendWait("{APPSKEY}")
          Start-Sleep -Milliseconds 500
          # Select "Install" from context menu
          [System.Windows.Forms.SendKeys]::SendWait("i")
          Start-Sleep -Milliseconds 500

      - name: Open Mouse Properties and Change Scheme
        run: |
          # Open Mouse Properties
          control main.cpl

          # Wait for Mouse Properties window to open
          Start-Sleep -Seconds 5

          # Send keys to change the scheme to Chroma S
          Add-Type -AssemblyName System.Windows.Forms
          [System.Windows.Forms.SendKeys]::SendWait("{TAB}")  # Navigate to Pointer Options tab
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("{DOWN}")  # Navigate to Scheme dropdown
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")  # Open Scheme dropdown
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("C")  # Select Chroma S scheme
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")  # Apply the changes

      - name: Enable Remote Desktop
        run: |
          # Enable TS
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

          # Enable Remote Desktop Firewall Rule
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # Set User Authentication for RDP
          Set-ItemProperty -Path 'HKLM:\Sy
