name: PC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download chroma_cur_black_s folder
        run: |
          $downloadUrl = "https://github.com/Dizaaar/FREE-RDP/raw/main/chroma_cur_black_s"
          $downloadPath = "C:\chroma_cur_black_s"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath -Method Download
          
      - name: Install using install.inf
        run: |
          $installInfPath = "C:\chroma_cur_black_s\install.inf"
          if (Test-Path $installInfPath) {
            Start-Process -FilePath "cmd.exe" -ArgumentList "/c $installInfPath"
          } else {
            Write-Host "install.inf not found in chroma_cur_black_s folder."
          }
          
      - name: Open Mouse Properties and Change Scheme
        run: |
          # Open Mouse Properties
          control main.cpl

          # Wait for Mouse Properties window to open
          Start-Sleep -Seconds 5

          # Send keys to change the scheme to Chroma S
          Add-Type -AssemblyName System.Windows.Forms
          [System.Windows.Forms.SendKeys]::SendWait("{TAB}")  # Navigate to Pointer Options tab
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("{DOWN}")  # Navigate to Scheme dropdown
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")  # Open Scheme dropdown
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("C")  # Select Chrome S scheme
          Start-Sleep -Milliseconds 500
          [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")  # Apply the changes
          
      - name: Enable Remote Desktop
        run: |
          # Enable TS
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

          # Enable Remote Desktop Firewall Rule
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # Set User Authentication for RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Local User Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
